apiVersion: v1
kind: Source
name: eventhub-source
spec:
  kind: EventHub
  properties:
    namespace: "<your-eventhub-namespace>"
    eventHub: "<your-eventhub-name>"
    consumerGroup: "$Default"
    connectionString:
      secretRef:
        vaultName: "<your-keyvault-name>"
        secretName: "eventhub-connection-string"
