apiVersion: v1
kind: ContinuousQuery
name: eventhub-query
spec:
  mode: query
  sources:
    subscriptions:
      - id: eventhub-source
  query: |
    MATCH (e:Event)
    RETURN e.id AS id,
           e.body AS body,
           e.enqueuedTime AS enqueuedTime
