apiVersion: v1
kind: DrasiProject
includes:
  - kind: sources
    pattern: "sources/*.yaml"
  - kind: queries
    pattern: "queries/*.yaml"
  - kind: reactions
    pattern: "reactions/*.yaml"
environments: {}
featureFlags: {}
secretMappings:
  - vaultName: "$(AZURE_KEY_VAULT_NAME)"
    secretName: eventhub-connection-string
    k8sSecret: eventhub-source-secrets
    k8sKey: connectionString
