apiVersion: v1
kind: DrasiProject
includes:
  - kind: sources
    pattern: "sources/*.yaml"
  - kind: queries
    pattern: "queries/*.yaml"
  - kind: reactions
    pattern: "reactions/*.yaml"
environments: {}
featureFlags: {}
